# Chapter 1 헬로 파이썬

## 1.1 파이썬이란?

- 배우기 쉬운 프로그래밍 언어
- 읽기 쉽고 성능 좋음
- 과학분야, 특히 기계학습과 데이터 과학 분야에서 널리 사용
    - 수치계산, 통계처리: Numpy, Scipy
    - 딥러닝 프레임워크: Caffe, TensorFlow, Chainer, Theano

## 1.2 파이썬 설치하기 (생략)

## 1.3 파이썬 인터프리터

파이썬 인터프리터는 대화모드라 하며, 개발자와 파이썬이 대화하듯 프로그래밍할 수 있다.

### 1.3.1 산술 연산 (생략)

### 1.3.2 자료형

클래스와 자료형을 같은 의미로 사용하는 경우가 많다.

In [9]:
type(10)

int

In [10]:
type(2.718)

float

In [11]:
type("hello")

str

### 1.3.3 변수

파이썬은 변수의 자료형을 상황에 맞게 자동으로 결정하는 동적 언어로 분류되는 프로그래밍 언어이다. 따라서 자동 형변환이 발생한다.

### 1.3.4 리스트

In [1]:
a = [1, 2, 3, 4, 5]

**인덱스**

In [2]:
a[0]

1

**슬라이싱**

In [3]:
a[0:2]

[1, 2]

In [4]:
a[1:]

[2, 3, 4, 5]

In [5]:
a[:-2]

[1, 2, 3]

### 1.3.5 딕셔너리

key, value 쌍으로 저장

In [6]:
me = {'height':180}

In [8]:
me['height']

180

In [9]:
me['weight'] = 70

In [10]:
print(me)

{'height': 180, 'weight': 70}


### 1.3.6 bool

bool은 참, 거짓 둘 중 하나를 갖는 자료형이다. and, or, not과 같은 논리 연산자를 사용할 수 있다.

In [15]:
hungry = True
sleepy = False

In [16]:
type(hungry)

bool

In [17]:
not hungry

False

In [18]:
hungry and sleepy

False

In [19]:
hungry or sleepy

True

### 1.3.7 if  문 ~ 1.3.9 함수 (생략)

## 1.4 파이썬 스크립트 파일

### 1.4.1 파일로 저장하기 (생략)

### 1.4.2 클래스

**클래스 구조**

In [20]:
class ClassName:
    def __init__(self, params):    # 생성자
        pass
    
    def method1(self, params):     # 메소드 1
        pass
    
    def method2(self, params):     # 메소드 2
        pass

\_\_init\_\_은 생성자의 역할을 하는 특수한 메소드이고, 클래스를 초기화하는 방법을 정의한다. 생성자는 클래스의 인스턴스가 만들어질 때 한번만 불린다.  
파이썬에서는 모든 메소드의 첫번째 인수로 자신(self)를 명시적으로 써주는 것이 특징이다.

In [21]:
class Man:
    def __init__(self, name):
        self.name = name
        print("Initialized!")
        
    def hello(self):
        print("Hello " + self.name + "!")
        
    def goodbye(self):
        print("Good-bye " + self.name + "!")

In [22]:
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


**인스턴스 변수**는 인스턴스별로 저장되는 변수이다. 위의 예제에서 self.name이 인스턴스 변수에 해당되고 self. 이후에 속성 이름을 써서 인스턴스 변수를 작성하거나 접근할 수 있다.

## 1.5 넘파이

딥러닝에서 행렬, 배열 계산이 많은데 넘파이에 행렬, 배열 관련된 유용한 메소드들이 많아서 자주 사용하게 된다. 대부분의 딥러닝 프레임워크의 가장 밑바닥 부분은 넘파이로 구현되어 있는 것을 볼 수 있다.

### 1.5.1 넘파이 가져오기

In [24]:
import numpy as np

### 1.5.2 넘파이 배열 생성하기

**np.array()**: 리스트를 인수로 받아 numpy.ndarray 반환

In [26]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [27]:
type(x)

numpy.ndarray

### 1.5.3 넘파이 산술 연산

In [28]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [29]:
x + y

array([3., 6., 9.])

In [30]:
x - y

array([-1., -2., -3.])

In [31]:
x * y

array([ 2.,  8., 18.])

In [32]:
x / y

array([0.5, 0.5, 0.5])

위의 예시는 element-wise 계산한 결과를 보여주는 예시이다. 주의할 점은 원소 수가 같아야 한다는 것이다.

**브로드캐스트**도 지원한다.

In [33]:
x = np.array([1.0, 2.0, 3.0])

In [34]:
x / 2.0

array([0.5, 1. , 1.5])

### 1.5.4 넘파이 N차원 배열 (행렬)

In [36]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [37]:
A.shape

(2, 2)

In [38]:
A.dtype

dtype('int32')

N차원 배열(행렬)도 산술 연산이 가능하고 마찬가지로 브로드캐스트 기능도 지원한다.

In [40]:
B = np.array([[3, 0], [3, 4]])

In [41]:
A + B

array([[4, 2],
       [6, 8]])

In [42]:
A * B

array([[ 3,  0],
       [ 9, 16]])

In [43]:
A * 10

array([[10, 20],
       [30, 40]])

※ 1차원 배열은 **벡터(vector)**, 2차원 배열을 **행렬(matrix)**라고 부르고 벡터와 행렬을 **텐서(tensor)**라고도 한다.

### 1.5.5 브로드캐스트

넘파이에서 shape이 다른 배열끼이나 스칼라와도 연산을 수행할 수 있는 기능을 **브로드캐스트**라고 한다.

In [44]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

In [45]:
A * B

array([[10, 40],
       [30, 80]])

다음과 같은 방식으로도 브로드캐스트가 작동한다.  
<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="500">

In [48]:
A = np.arange(9).reshape(3, 3)
B = np.arange(27).reshape(3, 3, 3)

In [49]:
A.shape, B.shape

((3, 3), (3, 3, 3))

In [51]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
print(B)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [54]:
A * B

array([[[  0,   1,   4],
        [  9,  16,  25],
        [ 36,  49,  64]],

       [[  0,  10,  22],
        [ 36,  52,  70],
        [ 90, 112, 136]],

       [[  0,  19,  40],
        [ 63,  88, 115],
        [144, 175, 208]]])

2차원 행렬과 3차원 행렬의 브로드캐스트도 정상적으로 작동한다.

### 1.5.6 원소 접근

In [55]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [56]:
X[0]

array([51, 55])

In [57]:
X[0][1]    # X[0,1]으로도 동일한 원소에 접근 가능하다.

55

In [58]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


for 문으로도 각 원소에 접근할 수 있지만 넘파이를 사용한다면 최대한 for 문을 사용하지 않는 것이 좋다.

In [59]:
X = X.flatten()    # X를 1차원 배열로 변환
print(X)

[51 55 14 19  0  4]


In [60]:
X[np.array([0, 2, 4])]    # X[[0, 2, 4]]과 동일

array([51, 14,  0])

In [62]:
X[X > 15]

array([51, 55, 19])

파이썬 리스트보다 확장된 인덱싱 방식을 지원하기 때문에 원하는 원소에 편리하게 접근할 수 있다.

## 1.6 matplotlib

데이터 시각화 관련 라이브러리