# Deep Learning from scratch 

# 밑바닥부터 시작하는 딥러닝

# Ch1

In [15]:
1+2

3

In [2]:
1-2

-1

In [3]:
4*5

20

In [4]:
7/5

1.4

In [5]:
3**2

9

In [6]:
type(10)

int

In [7]:
type(2.718)

float

In [8]:
type("hello")

str

In [11]:
x=10
print(x)

10


In [12]:
x=100
print(x)

100


In [13]:
y=3.14
x * y

314.0

In [14]:
type(x * y)

float

In [16]:
a=[1, 2, 3, 4, 5]
print(a)

[1, 2, 3, 4, 5]


In [19]:
len(a)

5

In [22]:
a[4]=99

In [23]:
print(a)

[1, 2, 3, 4, 99]


In [24]:
print(a)
a[0:2]

[1, 2, 3, 4, 99]


[1, 2]

In [25]:
a[1:]

[2, 3, 4, 99]

In [26]:
a[:3]

[1, 2, 3]

In [27]:
a[:-1]

[1, 2, 3, 4]

# 1.3.5 딕셔너리

In [29]:
me={'height':100}

In [30]:
me['height']

100

In [32]:
me['weight']=70
print(me)

{'height': 100, 'weight': 70}


In [34]:
hungry = True
sleepy = False

In [35]:
type(hungry)

bool

In [36]:
not hungry

False

In [38]:
hungry and sleepy

False

# 1.3.7 if 문

In [40]:
hungry = True
if hungry:
    print("I'm hungry")

I'm hungry


In [43]:
hungry = False 
if hungry:
    print("i'm not hungry")
else: 
    print("I'm not hungry")
    print("I'm sleepy")

I'm not hungry
I'm sleepy


# 1.3.8 for 문

In [44]:
for i in[1,2,3]:
    print(i)

1
2
3


# 1.3.9함수

In [45]:
def hello():
    print("Hello World!")

In [46]:
hello()

Hello World!


In [49]:
def hello(object):
    print("Hello " + object + "!")

In [50]:
hello('cat')

Hello cat!


# 1.4 파이썬 스크립트 파일

In [59]:
class Man:
    def __init__(self,name):
        self.name = name
        print("Initialized!")
    def hello(self):
        print("Hello " + self.name + "!")
    def goodbye(self):
        print("Good-bye " +  self.name + "!")

In [60]:
m = Man("David")

Initialized!


In [61]:
m.hello()

Hello David!


In [62]:
m.goodbye()

Good-bye David!


# 1.5 넘파이

In [63]:
import numpy as np

In [66]:
x= np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [67]:
type(x)

numpy.ndarray

In [68]:
# 원소별(element - wise) 연산. 각 array의 수가 다르면 오류 발생
x= np.array([1.0, 2.0, 3.0])
y= np.array([2.0, 4.0, 6.0])

In [69]:
x+y

array([3., 6., 9.])

In [70]:
x-y

array([-1., -2., -3.])

In [71]:
x*y

array([ 2.,  8., 18.])

In [72]:
x/y

array([0.5, 0.5, 0.5])

In [75]:
x = np.array([1.0, 2.0, 3.0])
x/2.0

array([0.5, 1. , 1.5])

In [76]:
# 다차원 배열
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [77]:
A.shape

(2, 2)

In [78]:
A.dtype

dtype('int32')

In [83]:
# 같은 형상의 행렬일 경우 (element wise 연산가능)
B = np.array([[3,0], [0,6]])
print(B)

[[3 0]
 [0 6]]


In [84]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [81]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [87]:
# 1.5.5 브로드 캐스트
A = np.array([[1,2], [3,4]])
B = np.array([10, 20])
A*B

array([[10, 40],
       [30, 80]])